server/index.js

get and post request | Joseph Nguyen

Working on get and post request.

---

database/dump.sql

added some default values to tables | Michael Poole

---

database/dump.sql

added default column to exercise table | Michael Poole

---

server/index.js

Completed post.

---

server/index.js

Completed delete end point.

---

client/components/table2.jsx
database/dump.sql

added customExercise table and modified dayExercise table | Michael Poole

---

server/index.js

Changed post.

---

client/components/default-list.jsx

Default list complete

---

client/components/app.jsx
client/components/table-days.jsx
client/components/table-row2.jsx
client/components/table2.jsx

made it so app has day in state and clicking days will update state | Michael Poole

---

server/index.js

Completed put end point.

---

client/components/table.jsx

added add exercise button to table

---

client/components/default-list-item.jsx

default list.

---

client/components/app.jsx
client/components/custom.jsx

you can create a custom exercise | Michael Poole

---

client/components/app.jsx
client/components/table-row.jsx
client/components/table.jsx
client/components/update-and-delete.jsx
client/components/update-exercise.jsx

user can view update entry screen and add button appears when no exercises exist

view update screen and add entry for days with no exercises

---

client/components/custom.jsx
client/components/header.jsx
server/public/styles.css

header updated

---

client/components/app.jsx
client/components/table-row.jsx
client/components/table.jsx
client/components/update-and-delete.jsx
client/components/update-exercise.jsx

update field enters text to change | Michael Poole

---

client/components/app.jsx
client/components/update-exercise.jsx

completed update feature | Michael Poole

---

client/components/app.jsx
client/components/default-list-item.jsx
client/components/default-list-item2.jsx
client/components/table-row.jsx

worked on default list accordion | Michael Poole

---

client/components/default-list-item.jsx

dynamically add body part names | Michael Poole

---

client/components/default-list-item-exercise.jsx
client/components/default-list-item.jsx
server/public/styles.css

completed accordion feature | Michael Poole

---

client/components/app.jsx

removing the container class from one of the div inside render method

app.jsx small update

---

client/components/app.jsx
client/components/custom.jsx
client/components/default-list-item-exercise.jsx
client/components/default-list-item.jsx
client/components/default-list.jsx

you can add exercises from default | Michael Poole

---

client/components/app.jsx
client/components/recommended-cal.jsx
server/public/styles.css

Recommended functionality

---

client/components/table.jsx
database/dump.sql
server/public/styles.css

fixed no scroll when there's a lot of exercises | Michael Poole

---

client/components/table-days.jsx

changed day sizing to full width of phone | Michael Poole

---

client/components/table.jsx
server/public/styles.css

add button is outside table | Michael Poole

---

server/public/styles.css

fixed opacity issue on modal
